<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="30777" started-at="2019-12-23T05:33:57Z" finished-at="2019-12-23T05:34:28Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="30777" started-at="2019-12-23T05:33:57Z" finished-at="2019-12-23T05:34:28Z">
      <class name="new_1.NewTest2">
        <test-method status="FAIL" signature="home()[pri:0, instance:new_1.NewTest2@2a2d45ba]" name="home" duration-ms="5" started-at="2019-12-23T05:34:28Z" finished-at="2019-12-23T05:34:28Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at new_1.NewTest2.home(NewTest2.java:15)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- home -->
      </class> <!-- new_1.NewTest2 -->
      <class name="new_1.NewTest">
        <test-method status="PASS" signature="Login()[pri:0, instance:new_1.NewTest@7c16905e]" name="Login" duration-ms="30724" started-at="2019-12-23T05:33:57Z" finished-at="2019-12-23T05:34:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login -->
      </class> <!-- new_1.NewTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
